<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../Fission.Abstractions/Fission.Abstractions.csproj" />
    <ProjectReference Include="../Fission.Engine/Fission.Engine.csproj" />
    <ProjectReference Include="../Fission.Runtime/Fission.Runtime.csproj" />
    <ProjectReference Include="../Fission.Scheduler/Fission.Scheduler.fsproj" />
  </ItemGroup>
</Project>
